"""Adding type and description to the LeafModel

Revision ID: 7158de42b4ac
Revises: 463f08b6366f
Create Date: 2025-06-14 13:21:12.124979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7158de42b4ac'
down_revision: Union[str, None] = '463f08b6366f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('leaves', sa.Column('type', sa.Enum('PAGE', 'PROJECT', name='leaftype'), nullable=False))
    op.add_column('leaves', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'order')
    op.drop_column('leaves', 'type')
    op.drop_column('leaves', 'description')
    # ### end Alembic commands ###
