"""Adding list of children_ids to LeafModel

Revision ID: d949852a5197
Revises: 7158de42b4ac
Create Date: 2025-06-14 13:40:46.832355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd949852a5197'
down_revision: Union[str, None] = '7158de42b4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('children_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'children_ids')
    # ### end Alembic commands ###
