/**
 * Leaf frontend: workspace bootstrap helpers (`frontend/src/lib/workspaceDefaults.ts`).
 *
 * Purpose:
 * - Ensures the workspace has baseline “default” leaves/databases:
 *   - a Journal database
 *   - today’s journal entry leaf (generated daily)
 *   - a “Notes Dump” scratch page
 *
 * How to read:
 * - The main export is `ensureWorkspaceDefaults()`, which:
 *   1) loads current tree leaves + database list
 *   2) ensures “Notes Dump” exists
 *   3) ensures “Journal” database exists (with a schema)
 *   4) ensures today’s journal row has a backing page
 *
 * Update:
 * - To change the default database schema, edit the `schema: { properties: [...] }` in `ensureJournalDatabase`.
 * - To adjust icons/titles, update `journalTitleFor`, `ensureNotesDump`, and `ensureDailyJournal`.
 *
 * Debug:
 * - If defaults aren’t created, check:
 *   - whether `ensureWorkspaceDefaults()` is called on the workspace home page
 *   - API failures inside the `Promise.all` / schema creation calls
 *   - `ensurePromise` caching: it should prevent repeated creation during a session.
 */
import { databasesApi, leavesApi, type Database, type Leaf } from './api'
import { createDatabaseAndEmit } from './databaseMutations'
import { createLeafAndPrimeCache, updateLeafAndPrimeCache } from './leafMutations'

export type WorkspaceDefaults = {
  dailyJournal: Leaf
  notesDump: Leaf
  journalDatabase: Database
  tagsDatabase: Database
}

let ensurePromise: Promise<WorkspaceDefaults> | null = null
let ensureResult: WorkspaceDefaults | null = null

function todayKey() {
  return new Date().toISOString().slice(0, 10)
}

function journalTitleFor(date: string) {
  return `Journal ${date}`
}

async function ensureNotesDump(leaves: Leaf[]) {
  const existing = leaves.find((leaf) => leaf.title === 'Notes Dump' && !leaf.database_id)
  if (existing) {
    return existing
  }

  return createLeafAndPrimeCache({
    title: 'Notes Dump',
    icon: { type: 'emoji', value: '📝' },
    description: null,
  }, { parent_id: null, kind: 'page' })
}

async function ensureJournalDatabase(databases: Database[]) {
  const existing = databases.find((database) => database.title === 'Journal')
  if (existing) {
    return existing
  }

  return createDatabaseAndEmit({
    title: 'Journal',
    icon: { type: 'emoji', value: '🗓️' },
    description: 'Daily journal entries generated by the workspace bootstrap.',
    schema: {
      properties: [
        { key: 'date', label: 'Date', type: 'text' },
      ],
    },
    view_type: 'table',
  })
}

async function ensureTagsDatabase(databases: Database[]) {
  const existing = databases.find((database) => database.title === 'Tags')
  if (existing) return existing

  return createDatabaseAndEmit({
    title: 'Tags',
    icon: { type: 'emoji', value: '🏷️' },
    description: 'Auto-managed tag index. Each tag becomes a page you can annotate.',
    schema: {
      properties: [
        { key: 'name', label: 'Name', type: 'text' },
      ],
    },
    view_type: 'table',
  })
}

async function ensureDailyJournal(leaves: Leaf[], journalDatabase: Database) {
  const date = todayKey()
  const expectedTitle = journalTitleFor(date)

  const existingLeaf = leaves.find((leaf) => leaf.database_id === journalDatabase.id && leaf.title === expectedTitle)
  if (existingLeaf) {
    return existingLeaf
  }

  const rows = await databasesApi.listRows(journalDatabase.id)
  const existingRow = rows.find((row) => String(row.properties?.date ?? '') === date && row.leaf_id)

  if (existingRow?.leaf_id) {
    const currentLeaf = await leavesApi.get(existingRow.leaf_id)
    if (currentLeaf.title !== expectedTitle || currentLeaf.icon?.value !== '🗓️') {
      return updateLeafAndPrimeCache(currentLeaf.id, {
        title: expectedTitle,
        database_id: journalDatabase.id,
        parent_id: currentLeaf.parent_id ?? null,
        children_ids: currentLeaf.children_ids,
        tags: currentLeaf.tags,
        icon: { type: 'emoji', value: '🗓️' },
      }, currentLeaf.content ?? null)
    }
    return currentLeaf
  }

  const row = await databasesApi.createRow(journalDatabase.id, {
    properties: { date },
  })

  if (!row.leaf_id) {
    throw new Error('Journal row did not create a backing page')
  }

  return updateLeafAndPrimeCache(row.leaf_id, {
    title: expectedTitle,
    database_id: journalDatabase.id,
    parent_id: null,
    children_ids: [],
    tags: [],
    icon: { type: 'emoji', value: '🗓️' },
  })
}

export async function ensureWorkspaceDefaults() {
  // Return cached result if defaults were already created this session
  if (ensureResult) return ensureResult
  if (ensurePromise) return ensurePromise

  ensurePromise = (async () => {
    const [leaves, databases] = await Promise.all([
      leavesApi.getTree().then(async (items) => Promise.all(items.map((item) => leavesApi.get(item.id)))),
      databasesApi.list(),
    ])

    const notesDump = await ensureNotesDump(leaves)
    const journalDatabase = await ensureJournalDatabase(databases)
    const tagsDatabase = await ensureTagsDatabase(databases)

    const refreshedLeaves = await leavesApi.getTree().then(async (items) => Promise.all(items.map((item) => leavesApi.get(item.id))))
    const dailyJournal = await ensureDailyJournal(refreshedLeaves, journalDatabase)

    return {
      dailyJournal,
      notesDump,
      journalDatabase,
      tagsDatabase,
    }
  })()

  try {
    ensureResult = await ensurePromise
    return ensureResult
  } finally {
    ensurePromise = null
  }
}

/** Reset the cached defaults (e.g. after rebuild-from-index). */
export function resetWorkspaceDefaultsCache() {
  ensureResult = null
  ensurePromise = null
}

/**
 * Ensure every tag in `tags` has a corresponding row (and backing leaf page)
 * in the Tags database. Creates missing entries; skips existing ones.
 */
export async function ensureTagEntries(tags: string[]) {
  if (tags.length === 0) return

  const databases = await databasesApi.list()
  const tagsDatabase = await ensureTagsDatabase(databases)

  const rows = await databasesApi.listRows(tagsDatabase.id)
  const existingNames = new Set(
    rows.map((row) => String(row.properties?.name ?? '').toLowerCase()),
  )

  for (const tag of tags) {
    if (existingNames.has(tag.toLowerCase())) continue

    const row = await databasesApi.createRow(tagsDatabase.id, {
      properties: { name: tag },
    })

    if (row.leaf_id) {
      await updateLeafAndPrimeCache(row.leaf_id, {
        title: tag,
        database_id: tagsDatabase.id,
        parent_id: null,
        children_ids: [],
        tags: [],
        icon: { type: 'emoji', value: '🏷️' },
      })
    }

    existingNames.add(tag.toLowerCase())
  }
}
